baseURL: https://selmirrrrr.github.io/abl
title: Association Bosniaque de Lausanne

# Multilingual configuration
defaultContentLanguage: fr
defaultContentLanguageInSubdir: true

languages:
  fr:
    languageName: Francais
    languageCode: fr-ch
    weight: 1
    title: Association Bosniaque de Lausanne
    params:
      description: Site officiel de l'Association Bosniaque de Lausanne
    menu:
      main:
        - name: Accueil
          url: /fr/#home
          weight: 10
        - name: À propos
          url: /fr/#about
          weight: 20
        - name: Services
          url: /fr/#services
          weight: 30
        - name: Blog
          url: /fr/blog/
          weight: 35
          identifier: blog
        - name: Événements
          url: /fr/events/
          weight: 40
          identifier: events
        - name: Comité
          url: /fr/comite/
          weight: 50
        - name: Prières
          url: /fr/#prayers
          weight: 60
        - name: Contact
          url: /fr/#contact
          weight: 100
  bs:
    languageName: Bosanski
    languageCode: bs-ba
    weight: 2
    title: Bosansko Udruzenje Lozana
    params:
      description: Sluzbena stranica Bosanskog Udruzenja Lausanne
    menu:
      main:
        - name: Početna
          url: /bs/#home
          weight: 10
        - name: O nama
          url: /bs/#about
          weight: 20
        - name: Usluge
          url: /bs/#services
          weight: 30
        - name: Blog
          url: /bs/blog/
          weight: 35
          identifier: blog
        - name: Događaji
          url: /bs/events/
          weight: 40
          identifier: events
        - name: Odbor
          url: /bs/comite/
          weight: 50
        - name: Vaktija
          url: /bs/#prayers
          weight: 60
        - name: Kontakt
          url: /bs/#contact
          weight: 100

# Site parameters
params:
  author: Association Bosniaque de Lausanne
  description: Site officiel de l'Association Bosniaque de Lausanne
  
# Build settings
build:
  writeStats: true # Needed for TailwindCSS

# Content management
taxonomies:
  category: categories
  tag: tags

# Permalinks
permalinks:
  blog: /blog/:year/:month/:slug/
  events: /events/:year/:month/:slug/
