baseURL: https://selmirrrrr.github.io/abl
title: Association Bosniaque de Lausanne

# Multilingual configuration
defaultContentLanguage: fr
defaultContentLanguageInSubdir: true

languages:
  fr:
    languageName: Francais
    languageCode: fr-ch
    weight: 1
    title: Association Bosniaque de Lausanne
    params:
      description: Site officiel de l'Association Bosniaque de Lausanne
    menu:
      main:
        - name: Accueil
          url: /#home
          weight: 10
        - name: À propos
          url: /#about
          weight: 20
        - name: Services
          url: /#services
          weight: 30
        - name: Événements
          url: /fr/events/
          weight: 40
          identifier: events
        - name: Contact
          url: /#contact
          weight: 50
  bs:
    languageName: Bosanski
    languageCode: bs-ba
    weight: 2
    title: Bosansko Udruzenje Lausanne
    params:
      description: Sluzbena stranica Bosanskog Udruzenja Lausanne
    menu:
      main:
        - name: Početna
          url: /#home
          weight: 10
        - name: O nama
          url: /#about
          weight: 20
        - name: Usluge
          url: /#services
          weight: 30
        - name: Događaji
          url: /bs/events/
          weight: 40
          identifier: events
        - name: Kontakt
          url: /#contact
          weight: 50

# Site parameters
params:
  author: Association Bosniaque de Lausanne
  description: Site officiel de l'Association Bosniaque de Lausanne
  
# Build settings
build:
  writeStats: true # Needed for TailwindCSS

# Content management
taxonomies:
  category: categories
  tag: tags

# Permalinks
permalinks:
  posts: /:year/:month/:slug/
  events: /:sections/:slug/
