name: Scrape Prayer Times

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour
  workflow_dispatch:     # Allow manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    env:
      TZ: 'Europe/Paris'  # Set timezone to Europe/Paris for consistent timing
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4
          
      - name: Run scraper
        run: python scripts/scrape_prayer_times.py
        
      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
      - name: Commit changes
        run: |
          git add data/prayers/prayer_times.json data/prayers/full_conf_data.json || true
          git add data/prayers/debug_last_html.html || true
          git diff --quiet && git diff --staged --quiet || git commit -m "Update prayer times [automated]"
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }} 