name: Scrape Prayer Times

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour
  workflow_dispatch:     # Allow manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    env:
      TZ: 'Europe/Paris'  # Set timezone to Europe/Paris for consistent timing
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4
          
      - name: Run scraper
        id: scraper
        run: |
          python scripts/scrape_prayer_times.py
          # Get the debug directory from the script's output
          DEBUG_DIR=$(python3 -c "import tempfile, os; print(os.path.join(tempfile.gettempdir(), 'prayer_times_debug'))")
          echo "debug_dir=$DEBUG_DIR" >> $GITHUB_OUTPUT
        
      - name: Upload debug files
        if: always()  # Upload even if the script fails
        uses: actions/upload-artifact@v3
        with:
          name: debug-files
          path: ${{ steps.scraper.outputs.debug_dir }}
          retention-days: 7
        
      - name: Check for changes
        id: check_changes
        run: |
          git status --porcelain
          echo "changes=$(git status --porcelain | wc -l)" >> $GITHUB_OUTPUT
        
      - name: Configure Git
        if: steps.check_changes.outputs.changes > 0
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
      - name: Commit and push changes
        if: steps.check_changes.outputs.changes > 0
        run: |
          echo "Changes detected, committing..."
          git add data/prayers/prayer_times.json
          git commit -m "Update prayer times [automated]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 